### ISSUE TITLE
Dubbo 3.2.11, using the tri protocol, the interface must implement the Async method

### ISSUE THREAD

**Issue by huaPeti** [apache/dubbo#13735]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here

After upgrading to 3.2.11, the previously defined interface using PB method encountered compilation errors and required the implementation of Async method, which is not compatible with the defined interface. We hope this issue can be resolved.

**Comment by huaPeti** [comment]
When troubleshooting the issue, it was found that the default method modified the permission range in the automatically generated abstract class during compilation, and all classes implementing this abstract class need to implement the aysnc method.



After reviewing the submission records, in a bug fix, fix tri stub unary method overload (# 13385) was modified. Is there any other way to solve the problem of method overload?

**Comment by AlbumenJ** [comment]
@EarthChen PTAL
