### ISSUE TITLE
[The Best Experience] the guide of customizing Dubbo 3.3.x to compatible with curator 4.x

### ISSUE THREAD

**Issue by slankka** [apache/dubbo#15719]
### Pre-check

- [x] I am sure that all the content I provide is in English.

### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Descriptions

I'm upgrading dubbo from 3.2.x to 3.3.x, to pick a best version to use 
* nacos+zookeeper
* double registry 
* one port for triple+dubbo protocol (the 3.3.x support HTTP payload to call triple port)

before we upgrade, we test compatibility with zookeeper + curator + dubbo

To take advantages of Service Discovery, we need curator-x-discovery, but our zookeeper server version is pretty low: 3.4.12, so we cannot use curator5, but we test that curator version 4.2.0 works with dubbo 3.2.4 pretty well for a long time, although dubbo need `dubbo-remoting-zookeeper-curator5`

```
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-x-discovery</artifactId>
            <version>4.2.0</version>
        </dependency>
```

When uprade dubbo to 3.3.14, we get:
```
WARN [main] o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext Exception encountered during context initialization - cancelling refresh attempt: java.lang.NoSuchMethodError: 'org.apache.curator.framework.CuratorFrameworkFactory$Builder org.apache.curator.framework.CuratorFrameworkFactory$Builder.ensembleTracker(boolean)'
```

When upgrade dubbo to lastet: 3.3.5, we get errors about zookeeper connection problem even upgrade zookeeper to 3.9.4. (impossible connect to zk server 3.4), to search the solution, some people give advices such as downgrade to jdk8 (not acceptable for us)
1. Unable to canonicalize address localhost/<unresolved>:7181 because it's not resolvable
2. https://issues.apache.org/jira/browse/ZOOKEEPER-3779

TLDR: for those people that still using old zookeeper registry, upgrade to 3.3.5 is possible, tested with curator 4.2.0 and zookeeper 3.4.12. The final advice is that ask your Dev department to upgrade zookeeper or change Nacos.

run Dubbo 3.3.x with zookeeper 3.4.12, just customize your dubbo:

change `Curator5ZookeeperClient` just one line of code, see the breaking changes: 

https://github.com/apache/dubbo/blob/a7b641f51e7166051c3006b3cc6f2e8a2dfd64f3/dubbo-remoting/dubbo-remoting-zookeeper-curator5/src/main/java/org/apache/dubbo/remoting/zookeeper/curator5/Curator5ZookeeperClient.java#L78

### Are you willing to submit a pull request to fix on your own?

- [x] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zrlw** [comment]
AS for me, you could customize your version since latest dubbo doesn't support low version of many softwares (not only ZK). It's just an open source

**Comment by slankka** [comment]
> AS for me, you could customize your version since latest dubbo doesn't support low version of many softwares (not only ZK). It's just an open source

Thanks for reasonable and quick response. Title and content are modified to provide clear information about customization.
