### ISSUE TITLE
dubbo2.6.5 not work with spring-boot-2.1.x

### ISSUE THREAD

**Issue by morisenmen** [apache/dubbo#3543]
I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

nacos-spring-boot-starter:0.2.1
spring-boot-starter:2.1.x
dubbo:2.6.5

### Expected Result

This problem is that spring-boot-2.1.x use tomcat-embed 9.x.And in that version has no Connector.setProtocol in it.

```
this is the error message:
An attempt was made to call the method org.apache.catalina.connector.Connector.setProtocol(Ljava/lang/String;)V but it does not exist. Its class, org.apache.catalina.connector.Connector, is available from the following locations:
```

**Comment by Zzij** [comment]
i have the same problem

**Comment by morisenmen** [comment]
java.lang.NoSuchMethodError: org.apache.catalina.connector.Connector.setProtocol(Ljava/lang/String;)V

at com.alibaba.dubbo.remoting.http.tomcat.TomcatHttpServer.<init>(TomcatHttpServer.java:63)
at com.alibaba.dubbo.remoting.http.tomcat.TomcatHttpBinder.bind(TomcatHttpBinder.java:28)
at com.alibaba.dubbo.remoting.http.HttpBinder$Adaptive.bind(HttpBinder$Adaptive.java)

**Comment by morisenmen** [comment]
In TomcatHttpServer.
The Code is not compatible could fix with this way
```
//        tomcat.getConnector().setProtocol("org.apache.coyote.http11.Http11NioProtocol");

        Context context = tomcat.addContext("/", baseDir);
        Tomcat.addServlet(context, "dispatcher", new DispatcherServlet());
        context.addServletMappingDecoded("/*", "dispatcher");
```
Protoco `org.apache.coyote.http11.Http11NioProtocol` in tomcat 9.This is default config,so it is not necessary.And ServletMapping set method is addServletMappingDecoded.

**Comment by AlbumenJ** [comment]
Please try upgrade to Dubbo 2.7.
