### ISSUE TITLE
[Q/A][Java SDK (Component)] Dubbo 3.x is not compatible with Spring Boot 2.1.x

### ISSUE THREAD

**Issue by marmot-z** [apache/dubbo#15106]
### Discussed in https://github.com/apache/dubbo/discussions/15105

<div type='discussions-op-text'>

<sup>Originally posted by **marmot-z** February  5, 2025</sup>
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Details

[In a commit in dubbo 3.x](https://github.com/apache/dubbo/pull/11950), after upgrading snakeyaml from 1.x to 2.x, the following exception will occur after starting spring boot starter 2.1.x: 

```
java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.Constructor: method <init>()V not found
at org.springframework.boot.env.OriginTrackedYamlLoader$OriginTrackingConstructor.<init>(OriginTrackedYamlLoader.java:82)
at org.springframework.boot.env.OriginTrackedYamlLoader$OriginTrackingConstructor.<init>(OriginTrackedYamlLoader.java:82)
at org.springframework.boot.env.OriginTrackedYamlLoader.createYaml(OriginTrackedYamlLoader.java:64)
at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:132)
at org.springframework.boot.env.OriginTrackedYamlLoader.load(OriginTrackedYamlLoader.java:75)
at org.springframework.boot.env.YamlPropertySourceLoader.load(YamlPropertySourceLoader.java:50)
....
```

The reason is that some obsolete methods were removed in snakeyaml 2.x, which caused spring boot to fail to load the corresponding method when it started. [This issue also mentioned it](https://github.com/apache/dubbo/pull/12399). 

The solution I can think of is to upgrade the spring boot version to 3.0.x to ensure that the snakeyaml versions used by dubbo and spring boot are compatible. However, upgrading the spring boot version has a wide range of impacts. I would like to ask if there are other solutions besides this? 🙏🙏🙏 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
</div>

**Comment by heliang666s** [comment]
Dubbo 3.2.2 and below still use SnakeYAML 1.x, and I believe the most time-saving and effortless approach is to use that version, as it is compatible with both Dubbo 3.x and Spring Boot 2.1.x. @marmot-z

**Comment by marmot-z** [comment]
Thanks for your reply, I will try this solution
