### ISSUE TITLE
dubbo 2.7.14 不兼容spring  boot 2.6.1

### ISSUE THREAD

**Issue by jinshengyong** [apache/dubbo#9394]
## dubbo 2.7.14 不兼容spring  boot 2.6.1，spring boot 2.5.x 一下兼容的，我升级到 spring boot 2.6.1 以后，dubbo 的健康检查就报错了

**Comment by jinshengyong** [comment]
# 版本
* spring boot 2.6.1
* spring cloud 2021.0.0 
* dubbo 2.7.14

# 报错信息
```2021-12-14 14:14:17.073 ERROR 13572 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Error processing condition on org.apache.dubbo.spring.boot.actuate.autoconfigure.DubboEndpointAnnotationAutoConfiguration.dubboEndpoint
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60)
	at org.apache.dubbo.spring.boot.actuate.endpoint.condition.CompatibleOnEnabledEndpointCondition.matches(CompatibleOnEnabledEndpointCondition.java:57)
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:193)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:153)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:129)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:343)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290)
	at cn.funtk.myshop.provider.ProviderApplication.main(ProviderApplication.java:19)
Caused by: java.util.NoSuchElementException: Unable to get attribute value for missing annotation
	at org.springframework.core.annotation.MissingMergedAnnotation.getAttributeValue(MissingMergedAnnotation.java:160)
	at org.springframework.core.annotation.AbstractMergedAnnotation.getRequiredAttributeValue(AbstractMergedAnnotation.java:217)
	at org.springframework.core.annotation.AbstractMergedAnnotation.getClass(AbstractMergedAnnotation.java:149)
	at org.springframework.boot.actuate.autoconfigure.endpoint.condition.OnAvailableEndpointCondition.getTarget(OnAvailableEndpointCondition.java:79)
	at org.springframework.boot.actuate.autoconfigure.endpoint.condition.OnAvailableEndpointCondition.getMatchOutcome(OnAvailableEndpointCondition.java:72)
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47)
	... 18 common frames omitted

```

**Comment by jinshengyong** [comment]
# 用以下版本就没问题
spring boot 2.5.7
spring cloud 2020.0.4
dubbo 2.7.14

**Comment by gitchenjh** [comment]
The root cause is that Spring Boot Actuator changed the implement of `org.springframework.boot.actuate.autoconfigure.endpoint.condition.ConditionOutcome#getMatchOutcome(ConditionContext context, AnnotatedTypeMetadata metadata)` in Spring Boot Actuator 2.6.x .  It requires endpoint beans annotationed directly by `org.springframework.boot.actuate.autoconfigure.endpoint.condition.ConditionalOnAvailableEndpoint`
![1639624363(1)](https://user-images.githubusercontent.com/24949156/146302351-c1ad252a-8b2e-4c80-ac6e-3f995f450ed3.jpg)
The  [org.apache.dubbo.spring.boot.actuate.endpoint.condition.CompatibleOnEnabledEndpointCondition](https://github.com/apache/dubbo/blob/master/dubbo-spring-boot/dubbo-spring-boot-actuator/src/main/java/org/apache/dubbo/spring/boot/actuate/endpoint/condition/CompatibleConditionalOnEnabledEndpoint.java) is not working with Spring Boot Actuator 2.6.x

根本原因是 Spring Boot Actuator  在 2.6.x 版本变更了`org.springframework.boot.actuate.autoconfigure.endpoint.condition#ConditionOutcome getMatchOutcome(ConditionContext context, AnnotatedTypeMetadata metadata)`的实现，现在 endpoint beans 必须直接被  `org.springframework.boot.actuate.autoconfigure.endpoint.condition.ConditionalOnAvailableEndpoint` 注解修饰
[org.apache.dubbo.spring.boot.actuate.endpoint.condition.CompatibleOnEnabledEndpointCondition](https://github.com/apache/dubbo/blob/master/dubbo-spring-boot/dubbo-spring-boot-actuator/src/main/java/org/apache/dubbo/spring/boot/actuate/endpoint/condition/CompatibleConditionalOnEnabledEndpoint.java) 和 Spring Boot Actuator 2.6.x版本不兼容

**Comment by gitchenjh** [comment]
Fixed in #9426

**Comment by StringKe** [comment]
> I tried and made a different mistake.
> 
> ```
> dubbo version: 3.0.4
> spring boot version: 2.6.1
> ```
> 
> ```shell
> Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/core/metrics/ApplicationStartup
> 	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:227)
> 	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:240)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290)
> 	at com.example.springboot.provider.ProviderApplication.main(ProviderApplication.java:10)
> Caused by: java.lang.ClassNotFoundException: org.springframework.core.metrics.ApplicationStartup
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> 	... 5 more
> ```

@icankeep Is this problem solved? I also encountered the same problem.
